# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy JAR app to Azure Web App - TouristGuideDel3

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main  # Kører ved PR til main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:     
      contents: read
      checks: write
      pull-requests: write  # Nødvendigt for at poste Surefire rapport til PR

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'microsoft'

      - name: Build with Maven (without running tests)
        run: mvn clean package -DskipTests

      - name: Publish Surefire Test Report
        if: success() || failure()  # Kører rapport uanset testresultat
        uses: scacap/action-surefire-report@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: '${{ github.workspace }}/target/*.jar'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # Required for JWT request
      contents: read # Required for actions/checkout
  
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_2E50D03C1F5B479E9A9F80D3E6CE4D1A }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_8C83075F8B174EAC831B56E960F7DEF8 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_CAD497F758A942B3BEB951C5F5CEB5DE }}

      - name: Set environment variables
        run: |
          echo "PROD_DATABASE_URL=${{ secrets.PROD_DATABASE_URL }}" >> $GITHUB_ENV
          echo "PROD_USERNAME=${{ secrets.PROD_USERNAME }}" >> $GITHUB_ENV
          echo "PROD_PASSWORD=${{ secrets.PROD_PASSWORD }}" >> $GITHUB_ENV

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'TouristGuideDel3'
          slot-name: 'Production'
          package: '*.jar'
          app-settings: |
            PROD_DATABASE_URL=${{ secrets.PROD_DATABASE_URL }}
            PROD_USERNAME=${{ secrets.PROD_USERNAME }}
            PROD_PASSWORD=${{ secrets.PROD_PASSWORD }}
